import React, { useState } from "react";
import Invoicehader from "../../../Component/Invoicesettingscomponents/Invoice/Invoicehader";
import Invoicearticle from "../../../Component/Invoicesettingscomponents/Invoice/Invoicearticle";
import InvoiceFooter from "../../../Component/Invoicesettingscomponents/Invoice/InvoiceFooter";
import Menuitems from "../../../Component/Invoicesettingscomponents/MenuItems";
import InvoiceNav from "../../../Component/Invoicesettingscomponents/InvoiceNav";

function EditInvoice() {
  const [selectedColor, setSelectedColor] = useState("#D3D3D3");

  const [headerData, setHeaderData] = useState({
    businessName: "Charmindu",
    phone: "+0725422146",
    email: "cnewa@gmail.com",
    address: "www.asipiya.lk",
    companyReg: "",
    website: "",
    billTo: "Smith Co. 123 Main Street City, CA 12345",
    shipTo: "John Smith 20637 Palm Drive City, CA 12345",
    terms: "John Smith 20637 Palm Drive City, CA 12345",
    paymentMethod: "Cash",
    InvoiceId: "12341",
    dueDate: "2025/09/10",
    showFields: {
      businessName: true,
      phone: true,
      email: true,
      address: true,
      companyReg: false,
      website: false,
      billingAddress: true,
      shipping: true,
      terms: true,
      dueDate: true,
      paymentMethod: true,
    },
  });

  const [articleData, setArticleData] = useState({
    items: [],
    terms: "",
  });

  const [footerData, setFooterData] = useState({
    notes: "Thank you for your business!",
    paymentDetails: "Bank Transfer: 123-456-789",
    footerText: "Invoice generated by Charmindu",
    showFields: {
      discounts: true,
      deposit: true,
      estimateSummary: true,
    },
  });

  const updateHeaderData = (field, value) => {
    setHeaderData((prev) => ({ ...prev, [field]: value }));
  };

  const updateArticleData = (field, value) => {
    setArticleData((prev) => ({ ...prev, [field]: value }));
  };

  const updateFooterData = (field, value) => {
    setFooterData((prev) => ({ ...prev, [field]: value }));
  };

  return (
    <div className="bg-gray-100 absolute top-[115px] right-0 w-full h-full overflow-auto p-4 sm:p-6 md:p-8 lg:p-10 animate-fadeIn pb-[150px]">
      <div className="bg-white p-6 rounded-md shadow-md w-full flex flex-row justify-between ">
        <Menuitems selectedColor={selectedColor} setSelectedColor={setSelectedColor} />
        <div className="w-[900px]">
          <Invoicehader headerData={headerData} selectedColor={selectedColor} />
          <Invoicearticle articleData={articleData} selectedColor={selectedColor} />
          <InvoiceFooter footerData={footerData} selectedColor={selectedColor} />
        </div>
      </div>
    </div>
  );
}

export default EditInvoice;