import React, { useState, useEffect } from "react";
import Invoicehader from "../../../Component/Invoicesettingscomponents/Invoice/ClassicInvoice/Invoicehader";
import Invoicearticle from "../../../Component/Invoicesettingscomponents/Invoice/ClassicInvoice/Invoicearticle";
import InvoiceFooter from "../../../Component/Invoicesettingscomponents/Invoice/ClassicInvoice/InvoiceFooter";
import MordenInvoiceHeader from "../../../Component/Invoicesettingscomponents/Invoice/MordenInvoice/Invoicehader";
import MordenInvoiceArticle from "../../../Component/Invoicesettingscomponents/Invoice/MordenInvoice/Invoicearticle";
import MordenInvoiceFooter from "../../../Component/Invoicesettingscomponents/Invoice/MordenInvoice/InvoiceFooter";
import MinimalInvoiceArticle from "../../../Component/Invoicesettingscomponents/Invoice/MinimalInvoice/MinimalInvoicearticle";
import MinimalInvoiceFooter from "../../../Component/Invoicesettingscomponents/Invoice/MinimalInvoice/MinimalInvoiceFooter";
import MinimalInvoiceHeader from "../../../Component/Invoicesettingscomponents/Invoice/MinimalInvoice/MinimalInvoicehader";
import ProfessionalInvoiceFooter from "../../../Component/Invoicesettingscomponents/Invoice/professionalInvoice/professionalInvoiceFooter";
import ProfessionalInvoicearticle from "../../../Component/Invoicesettingscomponents/Invoice/professionalInvoice/professionalInvoicearticle";
import ProfessionalInvoicehader from "../../../Component/Invoicesettingscomponents/Invoice/professionalInvoice/professionalInvoicehader";
import Menuitems from "../../../Component/Invoicesettingscomponents/MenuItems";

function EditInvoice() {
  const [selectedColor, setSelectedColor] = useState(localStorage.getItem('invoiceColor') || "#D3D3D3");
  const [selectedTemplate, setSelectedTemplate] = useState(localStorage.getItem('invoiceTemplate') || "Classic");
  
  const [headerData, setHeaderData] = useState(() => {
    const savedData = localStorage.getItem("headerData");
    return savedData ? JSON.parse(savedData) : {
      businessName: "Charmindu",
      phone: "+0725422146",
      email: "cnewa@gmail.com",
      address: "www.asipiya.lk",
      companyReg: "",
      website: "",
      billTo: "Smith Co. 123 Main Street City, CA 12345",
      shipTo: "John Smith 20637 Palm Drive City, CA 12345",
      terms: "John Smith 20637 Palm Drive City, CA 12345",
      paymentMethod: "Cash",
      InvoiceId: "12341",
      dueDate: "2025/09/10",
      showFields: {
        businessName: true,
        phone: true,
        email: true,
        address: true,
        companyReg: false,
        website: false,
        billingAddress: true,
        shipping: true,
        terms: true,
        dueDate: true,
        paymentMethod: true,
      },
    };
  });

  const [articleData, setArticleData] = useState(() => {
    const savedData = localStorage.getItem("articleData");
    return savedData ? JSON.parse(savedData) : { items: [], terms: "" };
  });

  const [footerData, setFooterData] = useState(() => {
    const savedData = localStorage.getItem("footerData");
    return savedData ? JSON.parse(savedData) : {
      notes: "Thank you for your business!",
      paymentDetails: "Bank Transfer: 123-456-789",
      footerText: "Invoice generated by Charmindu",
      showFields: {
        discounts: true,
        deposit: true,
        estimateSummary: true,
      },
    };
  });

  return (
    <div className="bg-gray-100 absolute top-[115px] right-0 w-full h-full overflow-auto p-4 sm:p-6 md:p-8 lg:p-10 animate-fadeIn">
      <div className="bg-white p-6 rounded-md shadow-md w-full flex flex-row justify-between">
        <Menuitems
          selectedColor={selectedColor}
          setSelectedColor={setSelectedColor}
          setSelectedTemplate={setSelectedTemplate}
          selectedTemplate={selectedTemplate}
        />
        <div id="invoice-preview" className="w-[900px] pb-10 border border-gray-300 rounded-lg p-6 bg-white">
          {selectedTemplate === "Classic" && (
            <>
              <Invoicehader headerData={headerData} selectedColor={selectedColor} />
              <Invoicearticle articleData={articleData} selectedColor={selectedColor} />
              <InvoiceFooter footerData={footerData} selectedColor={selectedColor} />
            </>
          )}
          {selectedTemplate === "Modern" && (
            <>
              <MordenInvoiceHeader headerData={headerData} selectedColor={selectedColor} />
              <MordenInvoiceArticle articleData={articleData} selectedColor={selectedColor} />
              <MordenInvoiceFooter footerData={footerData} selectedColor={selectedColor} />
            </>
          )}
          {selectedTemplate === "Minimal" && (
            <>
              <MinimalInvoiceHeader headerData={headerData} selectedColor={selectedColor} />
              <MinimalInvoiceArticle articleData={articleData} selectedColor={selectedColor} />
              <MinimalInvoiceFooter footerData={footerData} selectedColor={selectedColor} />
            </>
          )}
          {selectedTemplate === "Professional" && (
            <>
              <ProfessionalInvoicehader headerData={headerData} selectedColor={selectedColor} />
              <ProfessionalInvoicearticle articleData={articleData} selectedColor={selectedColor} />
              <ProfessionalInvoiceFooter footerData={footerData} selectedColor={selectedColor} />
            </>
          )}
        </div>
      </div>
    </div>
  );
}

export default EditInvoice;