import React, { useState } from "react";
import Invoicehader from "../../../Component/Invoicesettingscomponents/Invoice/Invoicehader";
import Invoicearticle from "../../../Component/Invoicesettingscomponents/Invoice/Invoicearticle";
import InvoiceFooter from "../../../Component/Invoicesettingscomponents/Invoice/InvoiceFooter";
import Menuitems from "../../../Component/Invoicesettingscomponents/MenuItems";
import Contentsettings from "../../../Component/Invoicesettingscomponents/Contentsettings";
import ContentSettings2 from "../../../Component/Invoicesettingscomponents/ContentSettings2";
import ContentSettings3 from "../../../Component/Invoicesettingscomponents/ContentSettings3";
import InvoiceNav from "../../../Component/Invoicesettingscomponents/InvoiceNav";
import DisplayInvoiceEmail from "../../../Component/Invoicesettingscomponents/DisplayInvoiceEmail/DisplayInvoiceEmail";

function EditInvoice() {
  // State for Invoice Header, Article, and Footer
  const [headerData, setHeaderData] = useState({
    businessName: "Charmindu",
    phone: "+0725422146",
    email: "cnewa@gmail.com",
    address: "www.asipiya.lk",
    companyReg: "",
    website: "",
    billTo: "Smith Co. 123 Main Street City, CA 12345",
    shipTo: "John Smith 20637 Palm Drive City, CA 12345",
    terms: "John Smith 20637 Palm Drive City, CA 12345",
    paymentMethod: "Cash",
    InvoiceId: "12341",
    dueDate: "2025/09/10",
    showFields: {
      businessName: true,
      phone: true,
      email: true,
      address: true,
      companyReg: false,
      website: false,
      billingAddress: true,
      shipping: true,
      terms: true,
      dueDate: true,
      paymentMethod: true,
    },
  });

  const [articleData, setArticleData] = useState({
    items: [],
    terms: "",
  });

  const [footerData, setFooterData] = useState({
    notes: "Thank you for your business!",
    paymentDetails: "Bank Transfer: 123-456-789",
    footerText: "Invoice generated by Charmindu",
    showFields: {
      discounts: true,
      deposit: true,
      estimateSummary: true,
    },
  });

  // Update functions for header, article, and footer data
  const updateHeaderData = (field, value) => {
    setHeaderData((prev) => ({ ...prev, [field]: value }));
  };

  const updateArticleData = (field, value) => {
    setArticleData((prev) => ({ ...prev, [field]: value }));
  };

  const updateFooterData = (field, value) => {
    setFooterData((prev) => ({ ...prev, [field]: value }));
  };

  return (
    <div className="bg-gray-100 absolute top-[115px] right-0 w-full h-full overflow-auto p-4 sm:p-6 md:p-8 lg:p-10 animate-fadeIn pb-[150px]">
      <div className="bg-white p-6 rounded-md shadow-md w-full flex flex-row justify-between ">
        <Menuitems />
        <div className="w-[900px]">
          {/* Pass headerData as a prop to Invoicehader */}
          <Invoicehader headerData={headerData} />

          {/* Pass articleData as a prop to Invoicearticle */}
          <Invoicearticle articleData={articleData} />

          {/* Pass footerData as a prop to InvoiceFooter */}
          <InvoiceFooter footerData={footerData} />
        </div>
      </div>
    </div>
  );
}

export default EditInvoice;