import React, { useState, useEffect } from "react";
import Invoicehader from "../../../Component/Invoicesettingscomponents/Invoice/ClassicInvoice/Invoicehader";
import Invoicearticle from "../../../Component/Invoicesettingscomponents/Invoice/ClassicInvoice/Invoicearticle";
import InvoiceFooter from "../../../Component/Invoicesettingscomponents/Invoice/ClassicInvoice/InvoiceFooter";
import Contentsettings from "../../../Component/Invoicesettingscomponents/Contentsettings";
import ContentSettings2 from "../../../Component/Invoicesettingscomponents/ContentSettings2";
import ContentSettings3 from "../../../Component/Invoicesettingscomponents/ContentSettings3";
import MordenInvoiceHeader from "../../../Component/Invoicesettingscomponents/Invoice/MordenInvoice/Invoicehader";
import MordenInvoiceArticle from "../../../Component/Invoicesettingscomponents/Invoice/MordenInvoice/Invoicearticle";
import MordenInvoiceFooter from "../../../Component/Invoicesettingscomponents/Invoice/MordenInvoice/InvoiceFooter";
import MinimalInvoiceArticle from "../../../Component/Invoicesettingscomponents/Invoice/MinimalInvoice/MinimalInvoicearticle";
import MinimalInvoiceFooter from "../../../Component/Invoicesettingscomponents/Invoice/MinimalInvoice/MinimalInvoiceFooter";
import MinimalInvoiceHeader from "../../../Component/Invoicesettingscomponents/Invoice/MinimalInvoice/MinimalInvoicehader";
import ProfessionalInvoiceFooter from "../../../Component/Invoicesettingscomponents/Invoice/professionalInvoice/professionalInvoiceFooter";
import ProfessionalInvoicearticle from "../../../Component/Invoicesettingscomponents/Invoice/professionalInvoice/professionalInvoicearticle";
import ProfessionalInvoicehader from "../../../Component/Invoicesettingscomponents/Invoice/professionalInvoice/professionalInvoicehader";

function Editinvoicecontent() {
  const [selectedSection, setSelectedSection] = useState("header");
  const [selectedColor, setSelectedColor] = useState(localStorage.getItem('invoiceColor') || "#D3D3D3");
  const [selectedTemplate, setSelectedTemplate] = useState(localStorage.getItem('invoiceTemplate') || "Classic");
  const [totalAmount, setTotalAmount] = useState(0);

  // Calculate total amount from invoice items
  const calculateTotalAmount = () => {
    const savedItems = localStorage.getItem("invoiceItems");
    if (!savedItems) return 0;
    
    const invoiceItems = JSON.parse(savedItems);
    return invoiceItems.reduce((total, item) => total + (item.amount || 0), 0);
  };

  // Update total amount when component mounts and when storage changes
  useEffect(() => {
    const updateTotal = () => {
      setTotalAmount(calculateTotalAmount());
    };

    // Initial calculation
    updateTotal();

    // Listen for changes in localStorage
    const handleStorageChange = () => {
      updateTotal();
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, []);

  // Retrieve data from localStorage or use default values
  const getStoredData = (key, defaultValue) => {
    const stored = localStorage.getItem(key);
    return stored ? JSON.parse(stored) : defaultValue;
  };

  const [headerData, setHeaderData] = useState(() =>
    getStoredData("headerData", {
      businessName: "Charmindu",
      phone: "+0725422146",
      email: "cnewa@gmail.com",
      address: "www.asipiya.lk",
      companyReg: "",
      website: "",
      billTo: "Smith Co. 123 Main Street City, CA 12345",
      shipTo: "John Smith 20637 Palm Drive City, CA 12345",
      terms: "John Smith 20637 Palm Drive City, CA 12345",
      paymentMethod: "Cash",
      InvoiceId: "12341",
      dueDate: "2025/09/10",
      showFields: {
        businessName: true,
        phone: true,
        email: true,
        address: true,
        companyReg: false,
        website: false,
        billingAddress: true,
        shipping: true,
        terms: true,
        dueDate: true,
        paymentMethod: true,
      },
    })
  );

  const [articleData, setArticleData] = useState(() =>
    getStoredData("articleData", {
      items: [],
      terms: "",
    })
  );

  const [footerData, setFooterData] = useState(() =>
    getStoredData("footerData", {
      notes: "Thank you for your business!",
      paymentDetails: "Bank Transfer: 123-456-789",
      footerText: "Invoice generated by Charmindu",
      showFields: {
        discounts: true,
        deposit: true,
        estimateSummary: true,
      },
    })
  );

  // Save data to localStorage when state changes
  useEffect(() => {
    localStorage.setItem("headerData", JSON.stringify(headerData));
  }, [headerData]);

  useEffect(() => {
    localStorage.setItem("articleData", JSON.stringify(articleData));
  }, [articleData]);

  useEffect(() => {
    localStorage.setItem("footerData", JSON.stringify(footerData));
  }, [footerData]);

  useEffect(() => {
    localStorage.setItem("invoiceTemplate", selectedTemplate);
  }, [selectedTemplate]);

  useEffect(() => {
    localStorage.setItem("invoiceColor", selectedColor);
  }, [selectedColor]);

  const updateHeaderData = (field, value) => {
    setHeaderData((prev) => {
      const updatedData = { ...prev, [field]: value };
      localStorage.setItem('headerData', JSON.stringify(updatedData));
      return updatedData;
    });
  };
  
  const updateArticleData = (field, value) => {
    setArticleData((prev) => {
      const updatedData = { ...prev, [field]: value };
      localStorage.setItem('articleData', JSON.stringify(updatedData));
      return updatedData;
    });
  };
  
  const updateFooterData = (field, value) => {
    setFooterData((prev) => {
      const updatedData = { ...prev, [field]: value };
      localStorage.setItem('footerData', JSON.stringify(updatedData));
      return updatedData;
    });
  };
  

  const toggleHeaderFieldVisibility = (field) => {
    setHeaderData((prev) => ({
      ...prev,
      showFields: { ...prev.showFields, [field]: !prev.showFields[field] },
    }));
  };

  const toggleFooterFieldVisibility = (field) => {
    setFooterData((prev) => ({
      ...prev,
      showFields: { ...prev.showFields, [field]: !prev.showFields[field] },
    }));
  };

  return (
    <div className="bg-gray-100 absolute top-[115px] right-0 w-full h-full overflow-auto p-4 sm:p-6 md:p-8 lg:p-10 animate-fadeIn">
      <div className="bg-white p-6 rounded-md shadow-md w-full flex flex-row justify-between">
        <div className="w-1/3">
          {selectedSection === "header" && (
            <Contentsettings
              headerData={headerData}
              updateHeaderData={updateHeaderData}
              toggleFieldVisibility={toggleHeaderFieldVisibility}
            />
          )}
          {selectedSection === "article" && (
            <ContentSettings2
              articleData={articleData}
              updateArticleData={updateArticleData}
            />
          )}
          {selectedSection === "footer" && (
            <ContentSettings3
              footerData={footerData}
              updateFooterData={updateFooterData}
              toggleFooterFieldVisibility={toggleFooterFieldVisibility}
            />
          )}
        </div>

        <div id="invoice-preview" className="w-[900px] pb-10 border border-gray-300 rounded-lg p-6 bg-white">
          {selectedTemplate === "Classic" && (
            <>
              <div onClick={() => setSelectedSection("header")}>
                <Invoicehader headerData={headerData} selectedColor={selectedColor} />
              </div>
              <div onClick={() => setSelectedSection("article")}>
                <Invoicearticle articleData={articleData} selectedColor={selectedColor} />
              </div>
              <div onClick={() => setSelectedSection("footer")}>
                <InvoiceFooter 
                  footerData={footerData} 
                  selectedColor={selectedColor} 
                  totalAmount={totalAmount} 
                />
              </div>
            </>
          )}
          {selectedTemplate === "Modern" && (
            <>
              <div onClick={() => setSelectedSection("header")}>
                <MordenInvoiceHeader headerData={headerData} selectedColor={selectedColor} />
              </div>
              <div onClick={() => setSelectedSection("article")}>
                <MordenInvoiceArticle articleData={articleData} selectedColor={selectedColor} />
              </div>
              <div onClick={() => setSelectedSection("footer")}>
                <MordenInvoiceFooter 
                  footerData={footerData} 
                  selectedColor={selectedColor} 
                  totalAmount={totalAmount} 
                />
              </div>
            </>
          )}
          {selectedTemplate === "Minimal" && (
            <>
              <div onClick={() => setSelectedSection("header")}>
                <MinimalInvoiceHeader headerData={headerData} selectedColor={selectedColor} />
              </div>
              <div onClick={() => setSelectedSection("article")}>
                <MinimalInvoiceArticle articleData={articleData} selectedColor={selectedColor} />
              </div>
              <div onClick={() => setSelectedSection("footer")}>
                <MinimalInvoiceFooter 
                  footerData={footerData} 
                  selectedColor={selectedColor} 
                  totalAmount={totalAmount} 
                />
              </div>
            </>
          )}
          {selectedTemplate === "Professional" && (
            <>
              <div onClick={() => setSelectedSection("header")}>
                <ProfessionalInvoicehader headerData={headerData} selectedColor={selectedColor} />
              </div>
              <div onClick={() => setSelectedSection("article")}>
                <ProfessionalInvoicearticle articleData={articleData} selectedColor={selectedColor} />
              </div>
              <div onClick={() => setSelectedSection("footer")}>
                <ProfessionalInvoiceFooter 
                  footerData={footerData} 
                  selectedColor={selectedColor} 
                  totalAmount={totalAmount} 
                />
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

export default Editinvoicecontent;